const form=document.getElementById('wl-form');
const steps=[...document.querySelectorAll('.step')];
let current=0;let completed=0;let saving=false;
const el=id=>document.getElementById(id);
function username(){return el('username').value.trim().replace(/^@/,'');}
function setError(id,message){el(id).textContent=message;}
function draw(){steps.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.toggle('complete',i<completed);s.querySelector('.step-body').hidden=i!==current;s.querySelector('.step-state').textContent=i<completed?'✓':i===current?'↓':'·';const edit=s.querySelector('.edit-step');if(edit)edit.hidden=i>=completed||saving;});el('level').textContent=completed+'/5';el('wl-progress').value=completed;}
function validUsername(){const ok=/^[A-Za-z0-9_]{1,15}$/.test(username());setError('username-error',ok?'':'Enter a valid X username (1–15 letters, numbers or underscores).');return ok;}
function validReply(){let ok=false;try{const u=new URL(el('reply-url').value.trim());const m=u.pathname.match(/^\/([A-Za-z0-9_]{1,15})\/status\/(\d+)\/?$/);ok=u.protocol==='https:'&&['x.com','www.x.com','twitter.com','www.twitter.com'].includes(u.hostname)&&!!m&&m[1].toLowerCase()===username().toLowerCase()&&m[2]!=='2105100048220713017';}catch{}setError('reply-error',ok?'':'Paste the link to your own reply, from the same X username as step 2.');return ok;}
function validWallet(){const ok=/^0x[a-fA-F0-9]{40}$/.test(el('wallet').value.trim())&&!/^0x0{40}$/i.test(el('wallet').value.trim());setError('wallet-error',ok?'':'Enter a non-zero EVM address: 0x followed by 40 hexadecimal characters.');return ok;}
el('follow-confirm').addEventListener('change',()=>{document.querySelector('[data-next="0"]').disabled=!el('follow-confirm').checked;});
el('like-confirm').addEventListener('change',()=>{document.querySelector('[data-next="2"]').disabled=!el('like-confirm').checked;});
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.next);if(i!==current)return;if(i===0&&!el('follow-confirm').checked)return;if(i===1&&!validUsername())return;if(i===2&&!el('like-confirm').checked)return;if(i===3&&!validReply())return;completed=i+1;current=completed;draw();const input=steps[current].querySelector('input:not([type=checkbox]),a');input?.focus({preventScroll:true});steps[current].scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});}));
document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{if(saving)return;current=Number(b.dataset.edit);completed=current;draw();steps[current].querySelector('input').focus();}));
form.addEventListener('submit',async e=>{e.preventDefault();if(saving||current!==4)return;setError('submit-error','');if(!validUsername()){current=1;completed=1;draw();return;}if(!validReply()){current=3;completed=3;draw();return;}if(!validWallet())return;if(!el('consent').checked){setError('submit-error','Please confirm that you agree to submit these details for review.');return;}saving=true;const button=el('submit-application');button.disabled=true;button.textContent='SAVING YOUR APPLICATION…';try{const endpoint=window.CRUMBS_CONFIG?.sheetsUrl?.trim();if(!endpoint)throw new Error('Registration is not connected yet. No application has been sent.');const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({username:username(),reply_url:el('reply-url').value.trim(),wallet:el('wallet').value.trim(),followed:el('follow-confirm').checked,liked_reposted:el('like-confirm').checked,consent:el('consent').checked,website:el('website').value})});const data=await response.json().catch(()=>({error:'Registration is unavailable right now. Your details have not been submitted.'}));if(!response.ok||data.ok!==true||!/^CR-[A-F0-9]{12}$/.test(data.application_id||''))throw new Error(data.error||'Could not save your application. Please try again.');completed=5;draw();form.hidden=true;el('success').hidden=false;el('application-id').textContent=data.application_id;el('success').scrollIntoView({behavior:'smooth',block:'center'});}catch(err){setError('submit-error',err.message||'Could not connect. Please try again.');}finally{saving=false;button.disabled=false;button.textContent='SEND MY APPLICATION →';}});
el('copy-id').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(el('application-id').textContent);el('copy-id').textContent='COPIED ✓';}catch{el('copy-id').textContent='SELECT AND COPY THE ID ABOVE';}});
draw();
